[package]
name = "ftui-pty"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ftui-core = { path = "../ftui-core" }
portable-pty = "0.8.1"
time = { version = "0.3", features = ["formatting"] }
